export const graphRoute = '/graph'
export const homeRoute = '/'
export const fileUploadRoute = '/uploadFile'
export const searchRoute = '/search'
export const profileRoute = '/profile'
export const datasetUploadRoute = '/uploadDataset'
