export const graphRoute = '/graph'
export const homeRoute = '/'
export const fileUploadRoute = '/uploadFile'
export const searchRoute = '/search'
export const datasetUploadRoute = '/uploadDataset'
export const researchPaperAnalysisRoute = '/researchAnalysis'