export const graphRoute = '/graph/:graphStateId?'
export const newGraphRoute = '/graph/'
export const homeRoute = '/'
export const searchRoute = '/search'
export const datasetRoute = '/dataset/'
export const newDatasetRoute = '/dataset/:datasetID?'
export const aboutRoute = '/about'
export const profileRoute = '/profile'
export const adminReviewRoute = '/adminReview'
export const userReviewRoute = '/userReview'

export const loginRoute = '/log-in'
export const signUpRoute = '/sign-up'
export const forgotPasswordRoute = '/api/v1/forgotPassword'

export const cellSizeAnalysisRoute = '/cellSizeAnalysis'
