export const graphRoute = '/graph/:graphStateId?'
export const newGraphRoute = '/graph/'
export const homeRoute = '/'
export const fileUploadRoute = '/uploadFile'
export const searchRoute = '/search'
export const datasetUploadRoute = '/uploadDataset'
export const researchPaperAnalysisRoute = '/researchAnalysis'
export const aboutRoute = '/about'
export const profileRoute = '/profile'

export const loginRoute = '/log-in'
export const signUpRoute = '/sign-up'
export const resetPasswordRoute = '/api/v1/resetPassword/:resetToken?'
export const forgotPasswordRoute = '/forgotPassword'

export const dataCellAnalysisRoute = '/dataCellAnalysis'
