export const graphRoute = '/graph/:graphStateId?'
export const newGraphRoute = '/graph/'
export const homeRoute = '/'
export const fileUploadRoute = '/uploadFile'
export const searchRoute = '/search'
export const datasetUploadRoute = '/dataset/'
export const newDatasetUploadRoute = '/dataset/:datasetID?'
export const researchPaperAnalysisRoute = '/researchAnalysis'
export const aboutRoute = '/about'
export const profileRoute = '/profile'
export const adminReviewRoute = '/adminReview'
export const userReviewRoute = '/userReview'

export const loginRoute = '/log-in'
export const signUpRoute = '/sign-up'
export const forgotPasswordRoute = '/api/v1/forgotPassword'

export const dataCellAnalysisRoute = '/dataCellAnalysis'
