// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('hideDatapoints', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('hideDatapoints', async function() {
    await driver.get("http://localhost:4500/")
    await driver.manage().window().setRect(1368, 872)
    {
      const element = await driver.findElement(By.css(".makeStyles-menuButton-4 path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".makeStyles-menuButton-4 path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Graph")).click()
    await driver.findElement(By.css(".MuiButton-textPrimary:nth-child(3) > .MuiButton-label")).click()
    await driver.findElement(By.css("#id2 > circle:nth-child(3)")).click()
    await driver.findElement(By.css("#id2 > circle:nth-child(5)")).click()
    await driver.findElement(By.css("#id2 > circle:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiGrid-grid-sm-7")).click()
    await driver.findElement(By.css(".MuiGrid-grid-sm-7")).click()
    await driver.findElement(By.css("circle:nth-child(6)")).click()
    await driver.findElement(By.css("#id0 > circle:nth-child(4)")).click()
    await driver.findElement(By.css("#id1 > circle:nth-child(1)")).click()
  })
})
