name: CI Build
on: 
  pull_request:
    branches: [master, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
          TEST_DB_TYPE: ${{ secrets.TEST_DB_TYPE }}
          TEST_HOST: ${{ secrets.TEST_HOST }}                              
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_PORT: ${{ secrets.TEST_PORT }}
          ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
      - run: |
          echo ${{ secrets.TEST_DB_PORT }} | sed 's/./& /g' 
          echo ${{ secrets.TEST_PORT }} | sed 's/./& /g' 
      - run: |
          cd Server && npm install && npx ts-node ./node_modules/typeorm/cli.js migration:run 
          npm run test
          echo ${#TEST_DB_PORT}
      - run: cd Server && npx ts-node ./node_modules/typeorm/cli.js migration:revert
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}