name: CI Build
on: 
  pull_request:
    branches: [master, develop]
defaults:
  run:
    working-directory: ./Server
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        with: 
            node_version: 14.x
        uses: actions/setup-node@v1
      - name: Run tests
        run: |                                          
          npm install
          npm run test
        with:
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
          TEST_DB_TYPE: ${{ secrets.TEST_DB_TYPE }}
          TEST_HOST: ${{ secrets.TEST_HOST }}                              
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_PORT: ${{ secrets.TEST_PORT }}
          ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}